### PR TITLE
Module matching per issue #235

### PR DESCRIPTION
**Pull request by labriola**
Let me know your thoughts on this approach. I didn't want to muck about too much in the code for a first PR but I also didn't want to copy the xfun implementation as its identical to the requirement for the module needs.

I am happy to revise so consider this preliminary

### CODE REVIEW

**Comment by labriola** [comment]
FYI, contributor agreement already submitted

**Comment by labriola** [comment]
(Part of the failure seems related to: test-retrieve.R:77: error: we can retrieve packages from git
cannot retrieve package 'skeleton' from 'git://github.com/kevinushey/skeleton.git'

**Comment by labriola** [comment]
Okay, I will take another stab and abandon this approach. I must be misinterpreting the action of the code regarding the ... and will look further. The general pattern of using import("foo") inside of a module is correctly captured correctly by this

**Comment by kevinushey** [comment]
My guess is that it might fail if someone used e.g. `modules::import("rnorm", from = "stats")`?

**Comment by labriola** [comment]
More than fair. I appreciate your time. I am on it

**Pull request closed without merging**
