### PR TITLE
Remove extra parenthesis in package-install.Rmd

### PR DESCRIPTION
**Pull request by damonbayer**

### CODE REVIEW

**Review by kevinushey — APPROVED** [review]
Thanks!

**Comment by damonbayer** [comment]
@kevinushey unfortunately, I am still unable to install `RNetCDF` using `renv`. I was, however, able to install it outside of `renv`. Any guesses if this is problem better solved by opening an issue in `renv` or `RNetCDF`?

**Comment by kevinushey** [comment]
Can you please open a separate issue with the full output you see in the error logs?

**Comment by damonbayer** [comment]
@kevinushey issue created: https://github.com/rstudio/renv/issues/2009

**Pull request merged**
