### PR TITLE
Don't auto-accept prompt when `load()`ing in auto-loader

### LINKED ISSUE #1543: renv::restore() runs automatically without prompting user
To reproduce, from the terminal:

```
cd $(mktemp -d)
R -e 'renv::init()'
R -e 'renv::record("rlang")'
```

Then, try starting R. You'll see something like:

```
$ R

R version 4.3.1 (2023-06-16) -- "Beagle Scouts"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: aarch64-apple-darwin20 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

- Project '/private/var/folders/9n/3nxsgkrj0rlfx196kzdttpww0000gn/T/tmp.oksvrpRh' loaded. [renv 1.0.0.9000]
- None of the packages recorded in the lockfile are installed.
- Using `renv::restore()` to restore the project library.
The following package(s) will be updated:

# Repository -----------------------------------------------------------------
- rlang   [* -> 1.1.1]

# Installing packages --------------------------------------------------------

- Installing rlang ...                          OK [linked from cache]
```

However, the code seems to indicate that we'd normally prompt the user here:

https://github.com/rstudio/renv/blob/63d8881e0947a544651cce394d2fc297650e34dd/R/load.R#L823-L828

Most likely this is the culprit:

https://github.com/rstudio/renv/blob/63d8881e0947a544651cce394d2fc297650e34dd/R/utils.R#L124-L128

but maybe we can just remove this code now?

### PR DESCRIPTION
**Pull request by hadley**
Fixes #1543 

I tested this in the terminal with:

```
cd $(mktemp -d)
R --quiet -e 'renv::init()'
R --quiet -e 'renv::record("rlang")'
R --quiet
```

And in RStudio with

```R
usethis::create_project("~/desktop/test")
renv::init()
renv::record("rlang")
# restart RStudio
```

### CODE REVIEW

**Comment by hadley** [comment]
This does not seem to be adequate within RStudio, and in fact you get a really confusing prompt where it looks like you're at the console, but it's actually a hidden confirmation dialog: 

Screenshot 2023-07-19 at 13 35 59

**Comment by hadley** [comment]
Ok, and that's because we also need to `load()` inside the hook.

**Comment by hadley** [comment]
The root cause of the check failures is https://bugs.launchpad.net/ubuntu/+source/curl/+bug/2028170

**Review by kevinushey — APPROVED** [review]

**Comment by hadley** [comment]
Need to add a news bulelt

**Comment by hadley** [comment]
@kevinushey do you want me to switch to using an explicit menu here instead? Maybe something like this?

```R
writef("- No packages recorded in the lockfile are installed.")
choice <- menu(
  "Restore the project library with `renv::restore()",
  "Leave project library empty"
)
```

**Comment by kevinushey** [comment]
Yeah, I like the idea of using a menu here.

**Review by kevinushey — APPROVED** [review]

**Pull request merged**
